baseURL = "https://yourdomain.com/"
languageCode = "en-us"
title = "Darshan Prajapati"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[pagination]
  pagerSize = 5

[params]
  [params.editPost]
    Text = "Suggest Changes"
    
  [params.homeInfoParams]
    Title = "Welcome! 👋"
    Content = "Hey, I’m Darshan! I build cool tech stuff, write about it, and share what I learn along the way. 🚀"
    
  [params.profileMode]
    enabled = true
    title = "Welcome! 👋"
    subtitle = "Hey, I’m Darshan! I build cool tech stuff, write about it, and share what I learn along the way. 🚀"
    imageUrl = "profile.png" 
    imageWidth = 120
    imageHeight = 120
    
    [[params.profileMode.buttons]]
      name = "Blog"
      url = "blogs"
      
    [[params.profileMode.buttons]]
      name = "Projects"
      url = "projects"
      
  [[params.socialIcons]]
    name = "medium"
    url = "https://medium.com/@mr.darshan2919"
  
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/darshan-prajapati29/"
  
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/thedarshannn"
    
  [[params.socialIcons]]
    name = "email"
    url = "mailto:your.email@example.com"

# Remove any font-related settings if they exist
# [params.assets]
#   disableFingerprinting = true

# Remove any customCSS references
# customCSS = ["css/custom-fonts.css"]

[menu]
  [[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    url = "/blogs/"
    weight = 10
    
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20
    
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40
